version: '3'
# Ryan Cheevers-Browen
# Docker Compose file for bWAPP
# CSEC 380 w/Olson - Assignment 4
# bWAPP: port 80



services:
  bwapp:
    image: raesene/bwapp
    container_name: bwapp
    ports: 
      - 8080:8080
    dns:
      - 10.0.1.10
    
  pma:
    image: phpmyadmin
    ports:
      - 80:80